128 synchronized blockchain
ubclaunchpad/cumulus pull request #129
Opened 2017-08-19 18:45 UTC by bfbachmann

## Related Issue
#128 

## Description
* This commit adds a lock to to the blockchain that we use in App so ensure there are no race conditions in validation/manipulation of blocks on the blockchain. Notice, when you read the code, that none of the functions in `blockchain.go` make use of this lock. That's because with almost everything we do with the blockchain we check if certain conditions to do with the blockchain are true, do some validation, and then append a block, so locking each one of those steps individually wouldn't work - they all need to be done as one atomic operation.
* I also updated `miner` so that it can be paused and resumed during normal operation.

## WIKI Updates
TODO

## Todos

General:
- [x] Tests
- [x] Documentation
- [ ] Wiki

Other (links to TODOs in code):
* Fix `TestEncodeDecodeBlockchain()`

2017-08-20 05:48 UTC, jordanschalm requested changes
Like this change but would like to see this package follow the same design as `app`

2017-08-20 05:48 UTC, jordanschalm commented on blockchain/blockchain_test.go
> +	// TODO: fix this
What's this?

2017-08-20 05:48 UTC, jordanschalm commented on miner/miner.go
> +func StopMining() {
I would like to see these incorporated into a struct like we did with app. Package level state is an antipattern, even if you only expect that state to be instantiated once

2017-08-20 05:48 UTC, jordanschalm commented on miner/miner.go
> +		if stateChanged() {
the `stateChanged` variable is probably unnecessary. Have you benchmarked this?

2017-08-22 04:41 UTC, bfbachmann commented on miner/miner.go
> +		if stateChanged() {
Good point, will refactor.

2017-08-22 04:42 UTC, bfbachmann commented on blockchain/blockchain_test.go
> +	// TODO: fix this
Oh right, that started failing when I added the lock to the blockchain for some strange reason. I didn't want to spend time figuring out what the problem was so I just commented it out. Will fix soon.

2017-08-23 05:48 UTC, jordanschalm approved these changes
👍 👍 
Two thumbs up

2017-08-23 05:48 UTC, jordanschalm commented on miner/miner.go
>  	// previously running mining job can be resumed or stopped.
Could define these values as type `MinerState` (I know it's not your code 😝 )

2017-08-23 05:48 UTC, jordanschalm commented on miner/miner.go
> +	Info     int
Similarly, could define type for this

2017-08-26 20:37 UTC, chadlagore commented on app/app.go
> +	a.Chain.Lock.Lock()
Can we just add a `Lock` method to the chain?

2017-08-26 21:10 UTC, chadlagore approved these changes
This is great! Maybe just change those test sleeps lengths if you can. :+1:

2017-08-26 21:10 UTC, chadlagore commented on app/console.go
This is a nice interface :tada:

2017-08-26 21:10 UTC, chadlagore commented on miner/miner.go
> +func (m *Miner) setState(state MinerState) {
:tada:

2017-08-26 21:10 UTC, chadlagore commented on miner/miner_test.go
> +	time.Sleep(time.Second / 2)
Just do `time.Millisecond * 50` - this type of stuff really slows our test suite down.

2017-08-26 22:16 UTC, merged