1 cumulus peer
ubclaunchpad/cumulus pull request #7
Opened 2017-05-06 18:53 UTC by bfbachmann

# What Changed:
- Added `cumuluspeer` with `MakeBasicHost` functionality 
- Updated `main.go` to take host port number, IP address and target peer to connect to as command line arguments
- Added tests for `cumuluspeer`

# Remaining TODOs
- Fix error with creating stream to peer:
```
ERROR net/identi: did not have own public key in Peerstore id.go:177
```
- Add more rigorous tests for `cumuluspeer`

2017-05-06 21:16 UTC, jordanschalm requested changes
Good job for your first Go code!

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +package cumuluspeer
Just call this `peer`. We know it's cumulus because inside the cumulus folder. Short and succinct package names

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +	DefaultIP		= "127.0.0.1" // Default Host IP address if none given
Run gofmt here.

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +	CumulusProtocol	= "/cumulate/0.0.1" // Cumulus communication protocol
Why `cumulate` instead of `cumulus`?

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +func MakeBasicHost(ip string, port int) (host.Host, pstore.Peerstore, error) {
You should wrap `host.Host` with your own struct `peer.Peer` and return that here. Also use the pattern `NewPeer` rather than `MakePeer`

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +func doCumulate(s net.Stream) {
This should be a method on the `Peer` struct
`func (p *Peer) Receive(s net.String) {...}`

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +	log.Info("Read: %s", str)
We should start making a distinction between `Log.Debug/Error/Warn`. This sort of stuff should be `Debug` or omitted

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +	log.Info("Done now. Bye!")
Debug here as well

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer.go
> +// Extracts target's the peer ID and multiaddress from the given multiaddress.
ExtractPeerInfo targets...

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer_test.go
> +package cumuluspeer_test
all files in the same folder have the same package name

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer_test.go
> +    cumuluspeer "github.com/ubclaunchpad/cumulus/cumuluspeer"
So we don't need this import

2017-05-06 21:16 UTC, jordanschalm commented on cumuluspeer/peer_test.go
> +func TestMakeBasicHostValidPort(t *testing.T) {
TestNew...

2017-05-06 21:16 UTC, jordanschalm commented on main.go
> +        select {} // Hang until someone connects to us
This will hang this goroutine forever, is that what we want?

2017-05-06 21:16 UTC, jordanschalm commented on main.go
> +    targetPeer := flag.String("t", "", "target peer to connect to")
If we know the IP and the port of the multiaddr can we infer the rest? A multiaddr as a CLI flag is an awkward ui

2017-05-06 21:24 UTC, chadlagore commented on cumuluspeer/peer.go
> +// Communicate with peers.
Re: https://golang.org/doc/effective_go.html#commentary. Function comments start with function name, ie `// doCumulate communicates with peers.`

2017-05-08 04:54 UTC, jordanschalm commented on peer/peer.go
> +	if err != nil {
Just `return stream, err` if you aren't handling error

2017-05-09 03:41 UTC, jordanschalm commented on peer/peer.go
> +func NewPeer(ip string, port int) (*Peer, error) {
If you're making a package with one primary export (ie `Peer`) then just call the constructor `New`. Then you're calling `peer.New(...)` -- makes more sense semantically

2017-05-13 21:14 UTC, merged